import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const poppins = Poppins({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <nav className="flex ">
          <Link href={"yugioh"}>Yu-Gi-Oh!</Link>
          <Link href={"pokemon"}>Pokémon</Link>
          <Link href={"other"}>Other</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
